run:
  deadline: 2m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - golint
    - megacheck
    - gocyclo
    - ineffassign
    - misspell
    - gocritic
    - govet

linters-settings:
  goimports:
  golint:
    min-confidence: 0
issues:
  exclude-use-default: false
  exclude:
    - (should have a package comment)
local-prefixes: k8s.io/kube-state-metrics
