sudo: required

language: go

go:
- 1.8

install:
- mkdir -p $HOME/gopath/src/k8s.io
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kube-state-metrics

jobs:
  include:
    - stage: E2e
      script: make e2e
