sudo: required

language: go

go:
    - "1.10.3"

install:
- mkdir -p $HOME/gopath/src/k8s.io
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kube-state-metrics

jobs:
  include:
    # Go fmt
    - script: make gofmtcheck
    # TODO: Re-enable once all collectors are refactored.
    # Check that all metrics are documented
    # - script: make doccheck
    # Unit Test
    - script: make test-unit
    # Build
    - script: make build
    # E2e
    - script: make e2e
