apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch", "get"]
- apiGroups: [""]
  resources:
  - nodes
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  verbs: ["list", "watch", "get", "update"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - replicasets
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]

