name: Kube-state-metrics CI checks

on:
  push:
    branches:
    - master
    - release*
    tags:
    - v1.*
    - v2.*
  pull_request:
    branches:
    - master
    - release*

env:
  E2E_SETUP_KIND: yes
  E2E_SETUP_KUBECTL: yes
  SUDO: sudo

jobs:
  job1:
    name: ci/go-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
        make lint

  job2:
    name: ci/validate-manifests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Validate generated manifests
      run: |
        make validate-manifests

  job3:
    name: ci/validate-go-modules
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Validate vendor is in sync with go modules
      run: |
        make validate-modules

  job4:
    name: ci/validate-docs
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Check that all metrics are documented
      run: |
        make doccheck

  job5:
    name: ci/unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Unit tests
      run: |
        make test-unit

  job6:
    name: ci/benchmark-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Benchmark tests
      run: |
        make test-benchmark-compare

  job7:
    name: ci/build-kube-state-merics
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: Build
      run: |
        make build

  job8:
    name: ci/e2e-tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: |
        go get -v -t -d ./...
        make install-tools

    - name: End-to-end tests
      run: |
        REGISTRY="quay.io/coreos" make e2e
