name: cron

on:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

env:
  GO_VERSION: "^1.19"

jobs:
  ci-security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Running govulncheck
        uses: Templum/govulncheck-action@latest
        with:
          go-version: ${{ env.GO_VERSION }}
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true
